# work flow : 들여쓰기 주의
name: github 실행

# event : main branch에 push될때
on:
  push:
    branches:
      - main
# 하나의 워크플로우 1개 이상의 job
# 여러job 은 병렬로 수행
jobs:
  # 임의로 부여한 job 이름
  My-Deploy-Job:
    # ubuntu 환경 최신버전 운영체제
    runs-on: ubuntu-latest

    # step : 특정 작업을 수행하는 가장 작은 단위
    # 여러 step 으로 구성
    steps:
      # step 이름
      - name: hello world
      # 리눅스코드
        run: echo "hello world"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "good"
          echo "morning"

      - name: github action 자체 내장 변수
        run: |
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
      - name: 보안이 중요
        run: |
          echo ${{secrets.MY_NAME}}
          echo ${{secrets.MY_HOBBY}}

      # 1. 내 저장소의 코드를 가상 환경으로 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 파이썬 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 파이썬 파일 실행 (main.py가 있다는 가정 하에)
      - name: Run script
        run: python main.py

